# Not sure if any other database works, I think I've used MariaDB syntax
debugmode: false
database:
  type: "mariadb"
  host: "localhost"
  port: "3306"
  user: "user"
  password: "password"
  database_name: "databaseName"